### PR TITLE
crypto: fix base58 encoding for BlsSignature

### LINKED ISSUE #49: `BlsSignature::from_base58_check` on valid inputs returns error "data too long"
**Describe the bug**
`BlsSignature::from_base58_check` on valid inputs returns error "data too long". This happens due to the following check:

https://github.com/trilitech/tezedge/blob/6675c1cc23c07194ee5c1d1f965ddeaed8bd382b/crypto/src/base58.rs#L73-L77

This check is incorrect. While `base58` crate works only for up to 128 _bytes_, base58 encoding for 128 bytes is a fair bit longer.

**To Reproduce**

```rust
#[test]
fn bls_signature_from_base58_check() {
    assert!(BlsSignature::from_base58_check("BLsigAmLKnuw12tethjMmotFPaQ6u4XCKrVk6c15dkRXKkjDDjHywbhS3nd4rBT31yrCvvQrS2HntWhDRu7sX8Vvek53zBUwQHqfcHRiVKVj1ehq8CBYs1Z7XW2rkL2XkVNHua4cnvxY7F").is_ok());
}
```
**Expected behavior**

The test passes, the call results in an `Ok` value

**Additional context**

N/A.

### PR DESCRIPTION
**Pull request by emturner**
The current base58 module incorrectly had a `128` char limit set on decoding hashes - too small for `bls sigs`. We raise this limit to the length of `BlsSigs` hashes, which are the longest hashes we support.

fixes #49

### CODE REVIEW

**Comment by lierdakil** [comment]
> The current base58 dep has a 128 byte limit

This is true, but 128 bytes is not the same as 128 base58 characters. 

> which is not long enough for bls sigs

This is false, `base58` will happily accept about 175-176 base58 characters, which corresponds to around 128 bytes. Bls signatures are mere 96 bytes, which corresponds to 142 characters in base58.

So this was never a problem with dependencies. I thought I explained it in the issue.

**Comment by emturner** [comment]
> > The current base58 dep has a 128 byte limit
> 
> This is true, but 128 bytes is not the same as 128 base58 characters.
> 
> > which is not long enough for bls sigs
> 
> This is false, `base58` will happily accept about 175-176 base58 characters, which corresponds to around 128 bytes. Bls signatures are mere 96 bytes, which corresponds to 142 characters (with prefix) in base58.
> 
> So this was never a problem with dependencies. I thought I explained it in the issue.

Ah thanks, apologies for the misunderstanding. Have updated

**Comment by lierdakil** [comment]
Hmm. I did some testing, and apparently I was under a few misconceptions. Apologies.

So while this works fine for bona fide Tezos hashes, there's an unfortunate landmine in the `base58` library related to handling zero data: it will panic if there are more than 128 leading characters `1` in the input (which translate to zero bytes). So that explains why the check in `from_base58check` was so strict.

Hence, it turns out, the library switch was a better overall fix.

Can you revert back to f625864? Again, sorry for this.

File: crypto/src/base58.rs [hunk 1]
```diff
@@ -18,9 +17,6 @@ pub enum FromBase58CheckError {
     /// The input is missing checksum.
     #[error("missing checksum")]
     MissingChecksum,
-    /// Data is too long
-    #[error("data too long")]
-    DataTooLong,
     #[error("mismatched data lenght: expected {expected}, actual {actual}")]
```
Comment (lierdakil) [inline crypto/src/base58.rs:20]:
```suggestion
    #[error("mismatched data length: expected {expected}, actual {actual}")]
```

While we're here, can we fix a typo?

File: crypto/src/base58.rs [hunk 2]
```diff
@@ -60,25 +56,19 @@ pub trait FromBase58Check {
...
 impl FromBase58Check for str {
     fn from_base58check(&self) -> Result<Vec<u8>, FromBase58CheckError> {
-        if self.len() > 128 {
-            return Err(FromBase58CheckError::DataTooLong);
-        }
-        match self.from_base58() {
+        match bs58::decode(self).into_vec() {
             Ok(payload) => {
                 if payload.len() >= Self::CHECKSUM_BYTE_SIZE {
                     let data_len = payload.len() - Self::CHECKSUM_BYTE_SIZE;
```
Comment (lierdakil) [inline crypto/src/base58.rs:74]: Perhaps we can avoid a redundant allocation here?

```rust
        match bs58::decode(self).into_vec() {
            Ok(mut payload) => {
                if payload.len() >= Self::CHECKSUM_BYTE_SIZE {
                    let data_len = payload.len() - Self::CHECKSUM_BYTE_SIZE;
                    let data = &payload[..data_len];
                    let checksum_provided = &payload[data_len..];

                    let checksum_expected = double_sha256(data);
                    let checksum_expected = &checksum_expected[..4];

                    if checksum_expected == checksum_provided {
                        // here, instead of allocating a new Vec, reuse payload with checksum stripped
                        payload.truncate(data_len);
                        Ok(payload)
                    } else {
                        Err(FromBase58CheckError::InvalidChecksum)
                    }
                } else {
                    Err(FromBase58CheckError::MissingChecksum)
                }
            }
            Err(_) => Err(FromBase58CheckError::InvalidBase58),
        }
```

**Review by lierdakil — APPROVED** [review]
LGTM with a couple suggestions.

File: crypto/src/base58.rs (hunk 2 above)
Comment (emturner) [reply crypto/src/base58.rs]: great spot! thanks, have done
