### PR TITLE
crypto: Signature of all zero bytes should be Unknown

### LINKED ISSUE #50: Base58-encoding signature consisting of all zero bytes produces `edsig` encoding, which doesn't match reference
**Describe the bug**

Base58-encoding signature consisting of all zero bytes produces `edsig` encoding, which doesn't match Octez implementation:

```bash
$ octez-client --mode mockup --protocol PtN normalize data 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 of type signature --unparsing-mode Readable
...
"sigMzJ4GVAvXEd2RjsKGfG2H9QvqTSKCZsuB2KiHbZRGFz72XgF6KaKADznh674fQgBatxw3xdHqTtMHUZAGRprxy64wg1aq"
```

but `tezos_crypto_rs::hash::Signature([0; 64].to_vec()).to_b58check()` produces `"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"`

Note, however, that base58-encoded ed25519 signature survives the round-trip:

```bash
$ octez-client --mode mockup --protocol PtN normalize data '"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"' of type signature --unparsing-mode Readable
"edsigtXomBKi5CTRf5cjATJWSyaRvhfYNHqSUGrn4SdbYRcGwQrUGjzEfQDTuqHhuA8b2d8NarZjz8TRf65WkpQmo423BtomS8Q"
```

**To Reproduce**

```rust
    #[test]
    fn test() {
        assert_eq!(
            &tezos_crypto_rs::hash::Signature([0; 64].to_vec()).to_b58check(),
            "sigMzJ4GVAvXEd2RjsKGfG2H9QvqTSKCZsuB2KiHbZRGFz72XgF6KaKADznh674fQgBatxw3xdHqTtMHUZAGRprxy64wg1aq"
        );
    }
```

**Expected behavior**

Test passes.

### PR DESCRIPTION
**Pull request by emturner**
Currently defaults to Ed25519, which does not match octez reference

Fixes #50

### CODE REVIEW

File: crypto/src/hash.rs [hunk 1]
```diff
@@ -465,12 +465,8 @@ impl HashType {
...
         } else {
             let mut hash = Vec::with_capacity(self.base58check_prefix().len() + data.len());
-            if matches!(self, Self::UnknownSignature) && data == [0; Self::Ed25519Signature.size()]
-            {
-                hash.extend(Self::Ed25519Signature.base58check_prefix());
-            } else {
-                hash.extend(self.base58check_prefix());
-            }
+
+            hash.extend(self.base58check_prefix());
```
Comment (lierdakil) [inline crypto/src/hash.rs:469]: There's also a mirror check in `b58check_to_hash`, which seems entirely redundant: if you have an `edsig` you wouldn't generally try to decode it as `sig` in the first place.

I'm referring to this piece of code specifically:

```rust
        if let HashType::UnknownSignature = self {
            // zero signature is represented as Ed25519 signature
            if hash.len()
                == HashType::Ed25519Signature.size()
                    + HashType::Ed25519Signature.base58check_prefix().len()
            {
                let (prefix, hash) =
                    hash.split_at(HashType::Ed25519Signature.base58check_prefix().len());
                if prefix == HashType::Ed25519Signature.base58check_prefix()
                    && hash == [0; HashType::Ed25519Signature.size()]
                {
                    return Ok(hash.to_vec());
                }
            }
        } else ...
```

Comment (emturner) [reply crypto/src/hash.rs:470]: done - removed this `if`
